# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21937594b0a4bdcf55bf28e1d23c8a88e7bf99367c5a6f404e1df9e1623642705ce182a5c258d73b43801e180b3d35bdc05d407d3b14b2e4ca43d6c186a6ed7c

test:
  secret_key_base: 3b0891e3b21eba72933dc9837b16b1d9a122a6ab328771bd0d76a518c4eb9004cd6231b388609d9b6f038e88febcdac8f083baa923f311914f20eb22cb4d8e5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
